# Site settings
title: Daily Victim Archive
description: "An archive of the old GameSpy Daily Victims."
url: "http://www.crzysdrs.sytes.net/dv/"
author:
  name: "Mitch Souders"
  email: "crzysdrs@gmail.com"
  url: "http://crzysdrs.sytes.net"

# Build settings
baseurl: /dv/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

exclude: [
  "gamespy.tar.gz",
  "README.md",
  "Build.hs",
  "dist",
  "shakefile.cabal",
  "stack.yaml",
  "_build"
  ]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: true

collections:
  article:
    output: true
    id: id    
  meta:
    output: true
    id: date
    permalink: /:collection/:path/
    
defaults:
  - scope:
      path: ""
      type: article
    values:
      layout: article
  - scope:
      path: ""
      type: meta
    values:
      layout: meta
      