# Site settings
title: Emerald | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Jacopo Rabolini"
  email: "hello@jacoporabolini.com"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: /dv/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

exclude: [
  "gamespy.tar.gz",
  "README.md",
  "Build.hs",
  "dist",
  "shakefile.cabal",
  "stack.yaml",
  "_build"
  ]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

collections:
  article:
    output: true
    id: id    
  meta:
    output: true
    id: date
    permalink: /:collection/:path/
    
defaults:
  - scope:
      path: ""
      type: article
    values:
      layout: article
  - scope:
      path: ""
      type: meta
    values:
      layout: meta
      